# SPDX-FileCopyrightText: Copyright (c) 2023-2026 Almaz Ilaletdinov <a.ilaletdinov@yandex.ru>
# SPDX-License-Identifier: MIT
---
name: 'anki-action'
description: 'Build anki cards from .md files'
branding:
  icon: alert-triangle
  color: orange
runs:
  using: 'docker'
  image: Dockerfile
inputs:
  path:
    description: 'The directory with .md files'
    required: false
    default: 'anki-cards'
outputs:
  path_to_file:
    description: 'File for anki app'
